### PR TITLE
Drag & Drop Funcitonality of various cards in different projects

### LINKED ISSUE #6: Implementing Drag and Drop in Cards in HomePage
Working on it, using dnd react library.

### PR DESCRIPTION
**Pull request by DevanshCodes**
Implemented the Drag and Drop functionality using react-beautiful-dnd library on the front side. 
image

### CODE REVIEW

**Comment by jaskiratsingh2000** [comment]
I am very curious to know this feature.

**Comment by jaskiratsingh2000** [comment]
Requesting a review from @devesh-verma

**Comment by DevanshCodes** [comment]
> I am very curious to know this feature.

You can use this using this build: https://deploy-preview-7--compassionate-mcnulty-c7e814.netlify.app/.
The netlify is building the PRs, just not posting the link here in the comments.

**Comment by DevanshCodes** [comment]
Hey! @vaibhavdaren @devesh-verma @jaskirat2000 Can this be merged?
Thanks!

**Comment by jaskiratsingh2000** [comment]
From myside this is good to go but I am trying to pitch @vaibhavdaren for approval

**Pull request merged**
