### PR TITLE
Popups for Login/SignUp

### LINKED ISSUE #3: Making the PopUps for the Login/SignUp Page!
Working on it.

### PR DESCRIPTION
**Pull request by DevanshCodes**
Popups are Added for Login and SignUp Screens using Bootstrap Modals and Bootstrap based forms. Styled them according to our Design.

### CODE REVIEW

**Comment by DevanshCodes** [comment]
image
image

@jaskirat2000 Please let me know if any design changes in these Popups. Thanks!

**Comment by DevanshCodes** [comment]
@jaskirat2000 I also pushed the changes according to Figma Design do let me know, if they are correct.
Thanks!

**Comment by jaskiratsingh2000** [comment]
Whenever you make any frontend related PR. You should always display the screenshot

**Comment by DevanshCodes** [comment]
image
Yup, sorry, the only reason I didn't attached the ss was because the netlify build was also there, I'll keep that in mind.

**Pull request merged**
