### PR TITLE
Initial Commits + Home page

### PR DESCRIPTION
**Pull request by DevanshCodes**
Sign Up form and Login Form is undergoing, apart from that Home page is completed.

### CODE REVIEW

**Comment by DevanshCodes** [comment]
@jaskirat2000 @vaibhavdaren

**Comment by jaskiratsingh2000** [comment]
If it's related to the frontend part, You should always mention screenshots
for it.

**Comment by DevanshCodes** [comment]
Okay, attaching.. We can add logos and stuff
image

**Comment by DevanshCodes** [comment]
image

**Pull request merged**
